Iter15
RIBorisov/URLShortener pull request #15
Opened 2024-06-25 05:47 UTC by RIBorisov

2024-06-27 22:54 UTC, s-shpak requested changes
Добавь, пожалуйста, компонент, который будет в отдельной горутине периодически полностьб удалять записи в хранилище, удаленные мягко

2024-06-27 22:54 UTC, s-shpak commented on init.sql
> -    id SERIAL PRIMARY KEY,
Теперь таблицу надо создавать при помощи механизма миграций: https://github.com/s-shpak/webinar-migrations

2024-06-27 22:54 UTC, s-shpak commented on init.sql
> +    short VARCHAR(200) NOT NULL UNIQUE,
Теперь, учитывая, что был добавлен `user_id`, `short` может повторяться для разных `user_id`

2024-06-27 22:54 UTC, s-shpak commented on internal/middleware/authorization.go
> +		ba.User.ID = userID
Это не будет работать в условии конкурентных запросов к севреу (подумай почему)

Лучше всего помещать это значение в контекст запроса (см. здесь как правильно определить ключи для объекта внутри контекста здесь https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint)

2024-06-27 22:54 UTC, s-shpak commented on internal/storage/postgres.go
>  		tableStmt = `CREATE TABLE IF NOT EXISTS urls (
После перехода на миграции это будет не нужно

2024-06-27 22:54 UTC, s-shpak commented on internal/storage/storage.go
> +	for _, u := range m.urls {
Этот цикл уже должен быть обернут в мьютекс, т.к. `u` ты получаешь за счет чтения мапы

2024-07-01 13:50 UTC, s-shpak requested changes

2024-07-01 13:50 UTC, s-shpak commented on go.mod
Когда я выполняю `go mod tidy`, файл меняется. Ты не настроил git-хуки для обновления `go mod` ?

2024-07-01 13:50 UTC, s-shpak commented on internal/storage/migrations/002_add_constraints.down.sql
Не вижу смысла создавать сразу несколько файлов миграции: версия твоего приложения будет полноценной после применения всех трех миграций, если применить не все, то приложение будет работать некорректно. Потому лучше объединить все в одну миграцию

2024-07-01 13:50 UTC, s-shpak commented on internal/storage/migrations/003_user_id_and_idx.up.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS idx_short_is_not_deleted ON urls (short) WHERE is_deleted = FALSE;
Такое же условие должно применяться к `long`

2024-07-01 13:50 UTC, s-shpak commented on internal/middleware/authorization.go
> +			if errors.Is(err, http.ErrNoCookie) {
Можно ли здесь уменьшить уровень вложенности

2024-07-01 13:50 UTC, s-shpak commented on internal/models/models.go
> +type UserID string
Это не очень хорошо, посмотри здесь, как можно лучше: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

2024-07-01 13:50 UTC, s-shpak commented on internal/storage/storage.go
>  	*logger.Log
А зачем встраивать логгер в эту структуру ?

2024-07-01 13:50 UTC, s-shpak commented on internal/storage/storage.go
> +	m.mux.Lock()
Почему мьютекс блокируется здесь, а не после строки 257? Или, если ты защищаешь мьютексом доступ к значению в контексте, почему `defer` вызывается на строке 258, а не после лока ?

2024-07-02 11:34 UTC, RIBorisov commented on internal/storage/migrations/002_add_constraints.down.sql
этим хотел показать как менялась таблица со временем, для "потомков"

2024-07-02 13:48 UTC, RIBorisov commented on internal/storage/storage.go
>  	*logger.Log
чтоб в горутине при удалении записать Error в лог

2024-07-02 14:03 UTC, RIBorisov commented on internal/storage/storage.go
>  	*logger.Log
плюс inMemory встраивается в inFile, где тоже используется

2024-07-05 08:21 UTC, s-shpak approved these changes

2024-07-05 10:40 UTC, merged