Iter23
RIBorisov/URLShortener pull request #23
Opened 2024-09-21 19:21 UTC by RIBorisov

2024-09-23 09:10 UTC, s-shpak requested changes

2024-09-23 09:10 UTC, s-shpak commented on cmd/shortener/main.go
> +	g.Go(func() error {
В `main.go` опять появляется довольно много логики. Постарайся перенести конфигурацию сервера внутрь приложения

2024-09-23 09:10 UTC, s-shpak commented on cmd/shortener/main.go
> +func prepareTLS(log *logger.Log) (string, string, error) {
Я посоветовал вынести бы эти действия в отдельную утилиту, а в самом приложении принимать путь к сертификату, который будет использоваться сервером

2024-09-23 09:10 UTC, s-shpak commented on cmd/shortener/main.go
> +	log.Info("graceful shutdown complete..")
Можно перенести на уровень `Debug`

2024-09-23 09:10 UTC, s-shpak commented on internal/config/config.go
> +	if _, err := os.Stat(configPath); os.IsNotExist(err) {
Нет смысла проверять файл на существование таким образом: файл может быть удален после `os.Stat`, или после `OsIsNotExist`, что делает бессмысленными эти проверки. Лучше ориентироваться на значение, возвращаемое `ReadConfig`

2024-09-23 15:16 UTC, RIBorisov commented on cmd/shortener/main.go
> +	g.Go(func() error {
уменьшил, остальное вроде как уместно

gracefulShutdown выносить в internal не вижу смысла

2024-09-23 15:20 UTC, RIBorisov commented on internal/config/config.go
> +	if _, err := os.Stat(configPath); os.IsNotExist(err) {
убрал проверку

2024-09-23 18:26 UTC, s-shpak requested changes

2024-09-23 18:26 UTC, s-shpak commented on internal/config/tls.go
> +func prepareTLS(log *logger.Log) (string, string, error) {
Я предложил бы тебе вынести это в отдельный `cmd/cert-generator` и добавить в `README.md` инструкции по генерации сертификатов и их использованию вместе с `shortener`. Кажется, что эта логика не должна быть частью `shortener`

2024-09-24 09:19 UTC, s-shpak approved these changes

2024-10-02 09:11 UTC, merged